### ISSUE TITLE
How can i read jpeg block mcu

### ISSUE THREAD

**Issue by HanalogInstruments** [Exaphis/python-jpeg-decoder#2]
Hi,

How can i read jpeg block mcu as grid like jpegsnoop?
![image](https://user-images.githubusercontent.com/100456607/175757658-48781b74-0dd7-45f2-8e85-ba11f276f209.png)

I have some jpeg have wrong demension and i want to know how to fix the 8x8 mcu like this:
https://www.disktuna.com/jpeg-visual-corruption/

My jpeg file: 
https://drive.google.com/file/d/1-cvmyrSfeJOONtCHNHSinLAj6cGFTQIZ/view?usp=sharing

In my case i repair jpeg encrypted by ransomware, it's encrypted 150kb from header just only raw data after SOS, so i use a random header from jpeg have same chroma sampling but the demension from header from sample jpeg and raw data difference.

i found a method to find width from raw data:
https://arxiv.org/pdf/1410.2100

**Comment by Exaphis** [comment]
Do you want to display the image with grids representing the MCUs? Sorry, not sure about the jpeg recovery specifically - I'm definitely not an expert in jpegs by any means. Seems like you already have help from others for that though.

**Comment by HanalogInstruments** [comment]
> Do you want to display the image with grids representing the MCUs? Sorry, not sure about the jpeg recovery specifically - I'm definitely not an expert in jpegs by any means. Seems like you already have help from others for that though.

Yes, could you detail how to define the mcu from jpeg?

**Comment by Exaphis** [comment]
The decoder says that the size of each MCU is 16 x 8. The relevant code is here: https://github.com/Exaphis/python-jpeg-decoder/blob/09b2aa333fd435f754fb0ec463c34f89684ef9f3/jpeg.py#L166-L174.

**Comment by HanalogInstruments** [comment]
> The decoder says that the size of each MCU is 16 x 8. The relevant code is here: https://github.com/Exaphis/python-jpeg-decoder/blob/09b2aa333fd435f754fb0ec463c34f89684ef9f3/jpeg.py#L166-L174.

![image](https://user-images.githubusercontent.com/100456607/175782760-23d374a6-5ea2-46b5-a2dc-2a7a18503ac9.png)

![image](https://user-images.githubusercontent.com/100456607/175783015-2d794224-7db4-40c9-b155-fee1413b7608.jpeg)

I really want to know how we read the gird mcu like this from bottom of image to get mcu lenght to insert to fix the image alignment issue, also i try to recover jpeg encrypted by ransomware and it have wrong demension and alignment issue

**Comment by Exaphis** [comment]
So you want to change the dimension of the image in order to fix the the alignment issue?

**Comment by HanalogInstruments** [comment]
> So you want to change the dimension of the image in order to fix the the alignment issue?

Yes, that's right

**Comment by HanalogInstruments** [comment]
> > So you want to change the dimension of the image in order to fix the the alignment issue?
> 
> Yes, that's right

You can use s2x1.jpg as header before FFDA and merger from the 153605(dec)byte to EOF of _NHL.jpg.nppp, and you can see we have wrong demension from header so i'm finding width estimating from jpeg and set height to 6000px by default to repair batch of files

**Comment by Exaphis** [comment]
You might be able to change the width/height by changing the number of lines and number of samples per line in the frame header.
